{% set name = "unsloth" %}
{% set version = "2025.6.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unsloth-{{ version }}.tar.gz
  sha256: 858b5360b7ba519c05d01cabe19bb9e9f04b8e7cab44a28949496bc15141d25a

build:
  noarch: python
  script:
    - sed -i.bak "s/protobuf<4.0.0/protobuf/g" pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - unsloth_zoo >=2025.6.4
    - pytorch >=2.4.0,<=2.7.0
    - xformers >=0.0.27.post2
    - bitsandbytes
    - triton >=3.0.0
    - packaging
    - tyro
    - transformers >=4.51.3,!=4.47.0,!=4.52.0,!=4.52.1,!=4.52.2
    - datasets >=3.4.1
    - sentencepiece >=0.2.0
    - tqdm
    - psutil
    - wheel >=0.42.0
    - numpy
    - accelerate >=0.34.1
    - trl >=0.7.9,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,!=0.15.0
    - peft >=0.7.1,!=0.11.0
    - protobuf
    - huggingface_hub
    - hf-transfer
    - diffusers
    - torchvision

test:
  # importing requires a GPU
  # imports:
  #   - unsloth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/unslothai/unsloth
  summary: 2-5X faster LLM finetuning
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
